// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: sistema.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entrenador struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Ranking       int32                  `protobuf:"varint,4,opt,name=ranking,proto3" json:"ranking,omitempty"`
	Estado        string                 `protobuf:"bytes,5,opt,name=estado,proto3" json:"estado,omitempty"`
	Suspension    int32                  `protobuf:"varint,6,opt,name=suspension,proto3" json:"suspension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entrenador) Reset() {
	*x = Entrenador{}
	mi := &file_sistema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entrenador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entrenador) ProtoMessage() {}

func (x *Entrenador) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entrenador.ProtoReflect.Descriptor instead.
func (*Entrenador) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{0}
}

func (x *Entrenador) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entrenador) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Entrenador) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Entrenador) GetRanking() int32 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *Entrenador) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *Entrenador) GetSuspension() int32 {
	if x != nil {
		return x.Suspension
	}
	return 0
}

type ListaEntrenadores struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entrenadores  []*Entrenador          `protobuf:"bytes,1,rep,name=entrenadores,proto3" json:"entrenadores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaEntrenadores) Reset() {
	*x = ListaEntrenadores{}
	mi := &file_sistema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaEntrenadores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaEntrenadores) ProtoMessage() {}

func (x *ListaEntrenadores) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaEntrenadores.ProtoReflect.Descriptor instead.
func (*ListaEntrenadores) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{1}
}

func (x *ListaEntrenadores) GetEntrenadores() []*Entrenador {
	if x != nil {
		return x.Entrenadores
	}
	return nil
}

type ResultadoOperacion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultadoOperacion) Reset() {
	*x = ResultadoOperacion{}
	mi := &file_sistema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoOperacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoOperacion) ProtoMessage() {}

func (x *ResultadoOperacion) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoOperacion.ProtoReflect.Descriptor instead.
func (*ResultadoOperacion) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{2}
}

func (x *ResultadoOperacion) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ResultadoOperacion) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type InfoTorneo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Nombre           string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Estado           string                 `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	GanadorId        string                 `protobuf:"bytes,3,opt,name=ganadorId,proto3" json:"ganadorId,omitempty"`
	GanadorNombre    string                 `protobuf:"bytes,4,opt,name=ganadorNombre,proto3" json:"ganadorNombre,omitempty"`
	NumParticipantes int32                  `protobuf:"varint,5,opt,name=numParticipantes,proto3" json:"numParticipantes,omitempty"`
	TorneoId         string                 `protobuf:"bytes,6,opt,name=torneoId,proto3" json:"torneoId,omitempty"` // Nuevo campo para ID del torneo
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InfoTorneo) Reset() {
	*x = InfoTorneo{}
	mi := &file_sistema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoTorneo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoTorneo) ProtoMessage() {}

func (x *InfoTorneo) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoTorneo.ProtoReflect.Descriptor instead.
func (*InfoTorneo) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{3}
}

func (x *InfoTorneo) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *InfoTorneo) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *InfoTorneo) GetGanadorId() string {
	if x != nil {
		return x.GanadorId
	}
	return ""
}

func (x *InfoTorneo) GetGanadorNombre() string {
	if x != nil {
		return x.GanadorNombre
	}
	return ""
}

func (x *InfoTorneo) GetNumParticipantes() int32 {
	if x != nil {
		return x.NumParticipantes
	}
	return 0
}

func (x *InfoTorneo) GetTorneoId() string {
	if x != nil {
		return x.TorneoId
	}
	return ""
}

type ListaTorneos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torneos       []*InfoTorneo          `protobuf:"bytes,1,rep,name=torneos,proto3" json:"torneos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaTorneos) Reset() {
	*x = ListaTorneos{}
	mi := &file_sistema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaTorneos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaTorneos) ProtoMessage() {}

func (x *ListaTorneos) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaTorneos.ProtoReflect.Descriptor instead.
func (*ListaTorneos) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{4}
}

func (x *ListaTorneos) GetTorneos() []*InfoTorneo {
	if x != nil {
		return x.Torneos
	}
	return nil
}

type SolicitudInscripcion struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EntrenadorId      string                 `protobuf:"bytes,1,opt,name=entrenadorId,proto3" json:"entrenadorId,omitempty"`
	EntrenadorNombre  string                 `protobuf:"bytes,2,opt,name=entrenadorNombre,proto3" json:"entrenadorNombre,omitempty"`
	EntrenadorRegion  string                 `protobuf:"bytes,3,opt,name=entrenadorRegion,proto3" json:"entrenadorRegion,omitempty"`
	EntrenadorRanking int32                  `protobuf:"varint,4,opt,name=entrenadorRanking,proto3" json:"entrenadorRanking,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SolicitudInscripcion) Reset() {
	*x = SolicitudInscripcion{}
	mi := &file_sistema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudInscripcion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudInscripcion) ProtoMessage() {}

func (x *SolicitudInscripcion) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudInscripcion.ProtoReflect.Descriptor instead.
func (*SolicitudInscripcion) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{5}
}

func (x *SolicitudInscripcion) GetEntrenadorId() string {
	if x != nil {
		return x.EntrenadorId
	}
	return ""
}

func (x *SolicitudInscripcion) GetEntrenadorNombre() string {
	if x != nil {
		return x.EntrenadorNombre
	}
	return ""
}

func (x *SolicitudInscripcion) GetEntrenadorRegion() string {
	if x != nil {
		return x.EntrenadorRegion
	}
	return ""
}

func (x *SolicitudInscripcion) GetEntrenadorRanking() int32 {
	if x != nil {
		return x.EntrenadorRanking
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_sistema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{6}
}

type SolicitudCombate struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CombateId          string                 `protobuf:"bytes,1,opt,name=combate_id,json=combateId,proto3" json:"combate_id,omitempty"`
	TorneoId           string                 `protobuf:"bytes,2,opt,name=torneo_id,json=torneoId,proto3" json:"torneo_id,omitempty"`
	Entrenador1Id      string                 `protobuf:"bytes,3,opt,name=entrenador1_id,json=entrenador1Id,proto3" json:"entrenador1_id,omitempty"`
	Entrenador2Id      string                 `protobuf:"bytes,4,opt,name=entrenador2_id,json=entrenador2Id,proto3" json:"entrenador2_id,omitempty"`
	GimnasioNombre     string                 `protobuf:"bytes,5,opt,name=gimnasio_nombre,json=gimnasioNombre,proto3" json:"gimnasio_nombre,omitempty"`              // Campo nuevo
	GimnasioRegion     string                 `protobuf:"bytes,6,opt,name=gimnasio_region,json=gimnasioRegion,proto3" json:"gimnasio_region,omitempty"`              // Campo nuevo
	Entrenador1Ranking int32                  `protobuf:"varint,7,opt,name=entrenador1_ranking,json=entrenador1Ranking,proto3" json:"entrenador1_ranking,omitempty"` // Nuevo campo para ranking del primer entrenador
	Entrenador2Ranking int32                  `protobuf:"varint,8,opt,name=entrenador2_ranking,json=entrenador2Ranking,proto3" json:"entrenador2_ranking,omitempty"` // Nuevo campo para ranking del segundo entrenador
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SolicitudCombate) Reset() {
	*x = SolicitudCombate{}
	mi := &file_sistema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudCombate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudCombate) ProtoMessage() {}

func (x *SolicitudCombate) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudCombate.ProtoReflect.Descriptor instead.
func (*SolicitudCombate) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{7}
}

func (x *SolicitudCombate) GetCombateId() string {
	if x != nil {
		return x.CombateId
	}
	return ""
}

func (x *SolicitudCombate) GetTorneoId() string {
	if x != nil {
		return x.TorneoId
	}
	return ""
}

func (x *SolicitudCombate) GetEntrenador1Id() string {
	if x != nil {
		return x.Entrenador1Id
	}
	return ""
}

func (x *SolicitudCombate) GetEntrenador2Id() string {
	if x != nil {
		return x.Entrenador2Id
	}
	return ""
}

func (x *SolicitudCombate) GetGimnasioNombre() string {
	if x != nil {
		return x.GimnasioNombre
	}
	return ""
}

func (x *SolicitudCombate) GetGimnasioRegion() string {
	if x != nil {
		return x.GimnasioRegion
	}
	return ""
}

func (x *SolicitudCombate) GetEntrenador1Ranking() int32 {
	if x != nil {
		return x.Entrenador1Ranking
	}
	return 0
}

func (x *SolicitudCombate) GetEntrenador2Ranking() int32 {
	if x != nil {
		return x.Entrenador2Ranking
	}
	return 0
}

type ResultadoCombate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CombateId     string                 `protobuf:"bytes,1,opt,name=combateId,proto3" json:"combateId,omitempty"`
	TorneoId      string                 `protobuf:"bytes,2,opt,name=torneoId,proto3" json:"torneoId,omitempty"`
	GanadorId     string                 `protobuf:"bytes,3,opt,name=ganadorId,proto3" json:"ganadorId,omitempty"`
	GanadorNombre string                 `protobuf:"bytes,4,opt,name=ganadorNombre,proto3" json:"ganadorNombre,omitempty"`
	Error         bool                   `protobuf:"varint,5,opt,name=error,proto3" json:"error,omitempty"`
	Mensaje       string                 `protobuf:"bytes,6,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultadoCombate) Reset() {
	*x = ResultadoCombate{}
	mi := &file_sistema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoCombate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoCombate) ProtoMessage() {}

func (x *ResultadoCombate) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoCombate.ProtoReflect.Descriptor instead.
func (*ResultadoCombate) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{8}
}

func (x *ResultadoCombate) GetCombateId() string {
	if x != nil {
		return x.CombateId
	}
	return ""
}

func (x *ResultadoCombate) GetTorneoId() string {
	if x != nil {
		return x.TorneoId
	}
	return ""
}

func (x *ResultadoCombate) GetGanadorId() string {
	if x != nil {
		return x.GanadorId
	}
	return ""
}

func (x *ResultadoCombate) GetGanadorNombre() string {
	if x != nil {
		return x.GanadorNombre
	}
	return ""
}

func (x *ResultadoCombate) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ResultadoCombate) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type ResultadoCombateDesdeRabbit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CombateId      string                 `protobuf:"bytes,1,opt,name=combate_id,json=combateId,proto3" json:"combate_id,omitempty"`
	TorneoId       string                 `protobuf:"bytes,2,opt,name=torneo_id,json=torneoId,proto3" json:"torneo_id,omitempty"`
	GanadorId      string                 `protobuf:"bytes,3,opt,name=ganador_id,json=ganadorId,proto3" json:"ganador_id,omitempty"`
	Entrenador1Id  string                 `protobuf:"bytes,4,opt,name=entrenador1_id,json=entrenador1Id,proto3" json:"entrenador1_id,omitempty"`
	Entrenador2Id  string                 `protobuf:"bytes,5,opt,name=entrenador2_id,json=entrenador2Id,proto3" json:"entrenador2_id,omitempty"`
	GimnasioNombre string                 `protobuf:"bytes,6,opt,name=gimnasio_nombre,json=gimnasioNombre,proto3" json:"gimnasio_nombre,omitempty"`
	Region         string                 `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	FechaCombate   string                 `protobuf:"bytes,8,opt,name=fecha_combate,json=fechaCombate,proto3" json:"fecha_combate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResultadoCombateDesdeRabbit) Reset() {
	*x = ResultadoCombateDesdeRabbit{}
	mi := &file_sistema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoCombateDesdeRabbit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoCombateDesdeRabbit) ProtoMessage() {}

func (x *ResultadoCombateDesdeRabbit) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoCombateDesdeRabbit.ProtoReflect.Descriptor instead.
func (*ResultadoCombateDesdeRabbit) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{9}
}

func (x *ResultadoCombateDesdeRabbit) GetCombateId() string {
	if x != nil {
		return x.CombateId
	}
	return ""
}

func (x *ResultadoCombateDesdeRabbit) GetTorneoId() string {
	if x != nil {
		return x.TorneoId
	}
	return ""
}

func (x *ResultadoCombateDesdeRabbit) GetGanadorId() string {
	if x != nil {
		return x.GanadorId
	}
	return ""
}

func (x *ResultadoCombateDesdeRabbit) GetEntrenador1Id() string {
	if x != nil {
		return x.Entrenador1Id
	}
	return ""
}

func (x *ResultadoCombateDesdeRabbit) GetEntrenador2Id() string {
	if x != nil {
		return x.Entrenador2Id
	}
	return ""
}

func (x *ResultadoCombateDesdeRabbit) GetGimnasioNombre() string {
	if x != nil {
		return x.GimnasioNombre
	}
	return ""
}

func (x *ResultadoCombateDesdeRabbit) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ResultadoCombateDesdeRabbit) GetFechaCombate() string {
	if x != nil {
		return x.FechaCombate
	}
	return ""
}

type VerificacionEntrenadores struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntrenadorIds []string               `protobuf:"bytes,1,rep,name=entrenadorIds,proto3" json:"entrenadorIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificacionEntrenadores) Reset() {
	*x = VerificacionEntrenadores{}
	mi := &file_sistema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificacionEntrenadores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificacionEntrenadores) ProtoMessage() {}

func (x *VerificacionEntrenadores) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificacionEntrenadores.ProtoReflect.Descriptor instead.
func (*VerificacionEntrenadores) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{10}
}

func (x *VerificacionEntrenadores) GetEntrenadorIds() []string {
	if x != nil {
		return x.EntrenadorIds
	}
	return nil
}

type ResultadoVerificacion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TodosValidos  bool                   `protobuf:"varint,1,opt,name=todosValidos,proto3" json:"todosValidos,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultadoVerificacion) Reset() {
	*x = ResultadoVerificacion{}
	mi := &file_sistema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoVerificacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoVerificacion) ProtoMessage() {}

func (x *ResultadoVerificacion) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoVerificacion.ProtoReflect.Descriptor instead.
func (*ResultadoVerificacion) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{11}
}

func (x *ResultadoVerificacion) GetTodosValidos() bool {
	if x != nil {
		return x.TodosValidos
	}
	return false
}

func (x *ResultadoVerificacion) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// Message for ranking updates
type RankingUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntrenadorId    string                 `protobuf:"bytes,1,opt,name=entrenador_id,json=entrenadorId,proto3" json:"entrenador_id,omitempty"`
	RankingAnterior int32                  `protobuf:"varint,2,opt,name=ranking_anterior,json=rankingAnterior,proto3" json:"ranking_anterior,omitempty"`
	RankingNuevo    int32                  `protobuf:"varint,3,opt,name=ranking_nuevo,json=rankingNuevo,proto3" json:"ranking_nuevo,omitempty"`
	TorneoId        string                 `protobuf:"bytes,4,opt,name=torneo_id,json=torneoId,proto3" json:"torneo_id,omitempty"` // Optional, to identify which tournament caused the change
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RankingUpdate) Reset() {
	*x = RankingUpdate{}
	mi := &file_sistema_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingUpdate) ProtoMessage() {}

func (x *RankingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingUpdate.ProtoReflect.Descriptor instead.
func (*RankingUpdate) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{12}
}

func (x *RankingUpdate) GetEntrenadorId() string {
	if x != nil {
		return x.EntrenadorId
	}
	return ""
}

func (x *RankingUpdate) GetRankingAnterior() int32 {
	if x != nil {
		return x.RankingAnterior
	}
	return 0
}

func (x *RankingUpdate) GetRankingNuevo() int32 {
	if x != nil {
		return x.RankingNuevo
	}
	return 0
}

func (x *RankingUpdate) GetTorneoId() string {
	if x != nil {
		return x.TorneoId
	}
	return ""
}

// Response after processing the ranking update
type RankingUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankingUpdateResponse) Reset() {
	*x = RankingUpdateResponse{}
	mi := &file_sistema_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingUpdateResponse) ProtoMessage() {}

func (x *RankingUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sistema_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingUpdateResponse.ProtoReflect.Descriptor instead.
func (*RankingUpdateResponse) Descriptor() ([]byte, []int) {
	return file_sistema_proto_rawDescGZIP(), []int{13}
}

func (x *RankingUpdateResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RankingUpdateResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_sistema_proto protoreflect.FileDescriptor

const file_sistema_proto_rawDesc = "" +
	"\n" +
	"\rsistema.proto\x12\asistema\"\x9e\x01\n" +
	"\n" +
	"Entrenador\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x18\n" +
	"\aranking\x18\x04 \x01(\x05R\aranking\x12\x16\n" +
	"\x06estado\x18\x05 \x01(\tR\x06estado\x12\x1e\n" +
	"\n" +
	"suspension\x18\x06 \x01(\x05R\n" +
	"suspension\"L\n" +
	"\x11ListaEntrenadores\x127\n" +
	"\fentrenadores\x18\x01 \x03(\v2\x13.sistema.EntrenadorR\fentrenadores\"D\n" +
	"\x12ResultadoOperacion\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"\xc8\x01\n" +
	"\n" +
	"InfoTorneo\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado\x12\x1c\n" +
	"\tganadorId\x18\x03 \x01(\tR\tganadorId\x12$\n" +
	"\rganadorNombre\x18\x04 \x01(\tR\rganadorNombre\x12*\n" +
	"\x10numParticipantes\x18\x05 \x01(\x05R\x10numParticipantes\x12\x1a\n" +
	"\btorneoId\x18\x06 \x01(\tR\btorneoId\"=\n" +
	"\fListaTorneos\x12-\n" +
	"\atorneos\x18\x01 \x03(\v2\x13.sistema.InfoTorneoR\atorneos\"\xc0\x01\n" +
	"\x14SolicitudInscripcion\x12\"\n" +
	"\fentrenadorId\x18\x01 \x01(\tR\fentrenadorId\x12*\n" +
	"\x10entrenadorNombre\x18\x02 \x01(\tR\x10entrenadorNombre\x12*\n" +
	"\x10entrenadorRegion\x18\x03 \x01(\tR\x10entrenadorRegion\x12,\n" +
	"\x11entrenadorRanking\x18\x04 \x01(\x05R\x11entrenadorRanking\"\a\n" +
	"\x05Empty\"\xd0\x02\n" +
	"\x10SolicitudCombate\x12\x1d\n" +
	"\n" +
	"combate_id\x18\x01 \x01(\tR\tcombateId\x12\x1b\n" +
	"\ttorneo_id\x18\x02 \x01(\tR\btorneoId\x12%\n" +
	"\x0eentrenador1_id\x18\x03 \x01(\tR\rentrenador1Id\x12%\n" +
	"\x0eentrenador2_id\x18\x04 \x01(\tR\rentrenador2Id\x12'\n" +
	"\x0fgimnasio_nombre\x18\x05 \x01(\tR\x0egimnasioNombre\x12'\n" +
	"\x0fgimnasio_region\x18\x06 \x01(\tR\x0egimnasioRegion\x12/\n" +
	"\x13entrenador1_ranking\x18\a \x01(\x05R\x12entrenador1Ranking\x12/\n" +
	"\x13entrenador2_ranking\x18\b \x01(\x05R\x12entrenador2Ranking\"\xc0\x01\n" +
	"\x10ResultadoCombate\x12\x1c\n" +
	"\tcombateId\x18\x01 \x01(\tR\tcombateId\x12\x1a\n" +
	"\btorneoId\x18\x02 \x01(\tR\btorneoId\x12\x1c\n" +
	"\tganadorId\x18\x03 \x01(\tR\tganadorId\x12$\n" +
	"\rganadorNombre\x18\x04 \x01(\tR\rganadorNombre\x12\x14\n" +
	"\x05error\x18\x05 \x01(\bR\x05error\x12\x18\n" +
	"\amensaje\x18\x06 \x01(\tR\amensaje\"\xac\x02\n" +
	"\x1bResultadoCombateDesdeRabbit\x12\x1d\n" +
	"\n" +
	"combate_id\x18\x01 \x01(\tR\tcombateId\x12\x1b\n" +
	"\ttorneo_id\x18\x02 \x01(\tR\btorneoId\x12\x1d\n" +
	"\n" +
	"ganador_id\x18\x03 \x01(\tR\tganadorId\x12%\n" +
	"\x0eentrenador1_id\x18\x04 \x01(\tR\rentrenador1Id\x12%\n" +
	"\x0eentrenador2_id\x18\x05 \x01(\tR\rentrenador2Id\x12'\n" +
	"\x0fgimnasio_nombre\x18\x06 \x01(\tR\x0egimnasioNombre\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12#\n" +
	"\rfecha_combate\x18\b \x01(\tR\ffechaCombate\"@\n" +
	"\x18VerificacionEntrenadores\x12$\n" +
	"\rentrenadorIds\x18\x01 \x03(\tR\rentrenadorIds\"U\n" +
	"\x15ResultadoVerificacion\x12\"\n" +
	"\ftodosValidos\x18\x01 \x01(\bR\ftodosValidos\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"\xa1\x01\n" +
	"\rRankingUpdate\x12#\n" +
	"\rentrenador_id\x18\x01 \x01(\tR\fentrenadorId\x12)\n" +
	"\x10ranking_anterior\x18\x02 \x01(\x05R\x0frankingAnterior\x12#\n" +
	"\rranking_nuevo\x18\x03 \x01(\x05R\frankingNuevo\x12\x1b\n" +
	"\ttorneo_id\x18\x04 \x01(\tR\btorneoId\"G\n" +
	"\x15RankingUpdateResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje2\xfc\x04\n" +
	"\n" +
	"LCPService\x12F\n" +
	"\x18ObtenerListaEntrenadores\x12\x0e.sistema.Empty\x1a\x1a.sistema.ListaEntrenadores\x127\n" +
	"\x0eObtenerTorneos\x12\x0e.sistema.Empty\x1a\x15.sistema.ListaTorneos\x12Q\n" +
	"\x13InscribirEntrenador\x12\x1d.sistema.SolicitudInscripcion\x1a\x1b.sistema.ResultadoOperacion\x12F\n" +
	"\x0eAsignarCombate\x12\x19.sistema.SolicitudCombate\x1a\x19.sistema.ResultadoCombate\x12G\n" +
	"\x13RegistrarEntrenador\x12\x13.sistema.Entrenador\x1a\x1b.sistema.ResultadoOperacion\x12[\n" +
	"\x16EnviarResultadoCombate\x12$.sistema.ResultadoCombateDesdeRabbit\x1a\x1b.sistema.ResultadoOperacion\x12Z\n" +
	"\x15VerificarEntrenadores\x12!.sistema.VerificacionEntrenadores\x1a\x1e.sistema.ResultadoVerificacion\x12P\n" +
	"\x16NotificarCambioRanking\x12\x16.sistema.RankingUpdate\x1a\x1e.sistema.RankingUpdateResponseB\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_sistema_proto_rawDescOnce sync.Once
	file_sistema_proto_rawDescData []byte
)

func file_sistema_proto_rawDescGZIP() []byte {
	file_sistema_proto_rawDescOnce.Do(func() {
		file_sistema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sistema_proto_rawDesc), len(file_sistema_proto_rawDesc)))
	})
	return file_sistema_proto_rawDescData
}

var file_sistema_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_sistema_proto_goTypes = []any{
	(*Entrenador)(nil),                  // 0: sistema.Entrenador
	(*ListaEntrenadores)(nil),           // 1: sistema.ListaEntrenadores
	(*ResultadoOperacion)(nil),          // 2: sistema.ResultadoOperacion
	(*InfoTorneo)(nil),                  // 3: sistema.InfoTorneo
	(*ListaTorneos)(nil),                // 4: sistema.ListaTorneos
	(*SolicitudInscripcion)(nil),        // 5: sistema.SolicitudInscripcion
	(*Empty)(nil),                       // 6: sistema.Empty
	(*SolicitudCombate)(nil),            // 7: sistema.SolicitudCombate
	(*ResultadoCombate)(nil),            // 8: sistema.ResultadoCombate
	(*ResultadoCombateDesdeRabbit)(nil), // 9: sistema.ResultadoCombateDesdeRabbit
	(*VerificacionEntrenadores)(nil),    // 10: sistema.VerificacionEntrenadores
	(*ResultadoVerificacion)(nil),       // 11: sistema.ResultadoVerificacion
	(*RankingUpdate)(nil),               // 12: sistema.RankingUpdate
	(*RankingUpdateResponse)(nil),       // 13: sistema.RankingUpdateResponse
}
var file_sistema_proto_depIdxs = []int32{
	0,  // 0: sistema.ListaEntrenadores.entrenadores:type_name -> sistema.Entrenador
	3,  // 1: sistema.ListaTorneos.torneos:type_name -> sistema.InfoTorneo
	6,  // 2: sistema.LCPService.ObtenerListaEntrenadores:input_type -> sistema.Empty
	6,  // 3: sistema.LCPService.ObtenerTorneos:input_type -> sistema.Empty
	5,  // 4: sistema.LCPService.InscribirEntrenador:input_type -> sistema.SolicitudInscripcion
	7,  // 5: sistema.LCPService.AsignarCombate:input_type -> sistema.SolicitudCombate
	0,  // 6: sistema.LCPService.RegistrarEntrenador:input_type -> sistema.Entrenador
	9,  // 7: sistema.LCPService.EnviarResultadoCombate:input_type -> sistema.ResultadoCombateDesdeRabbit
	10, // 8: sistema.LCPService.VerificarEntrenadores:input_type -> sistema.VerificacionEntrenadores
	12, // 9: sistema.LCPService.NotificarCambioRanking:input_type -> sistema.RankingUpdate
	1,  // 10: sistema.LCPService.ObtenerListaEntrenadores:output_type -> sistema.ListaEntrenadores
	4,  // 11: sistema.LCPService.ObtenerTorneos:output_type -> sistema.ListaTorneos
	2,  // 12: sistema.LCPService.InscribirEntrenador:output_type -> sistema.ResultadoOperacion
	8,  // 13: sistema.LCPService.AsignarCombate:output_type -> sistema.ResultadoCombate
	2,  // 14: sistema.LCPService.RegistrarEntrenador:output_type -> sistema.ResultadoOperacion
	2,  // 15: sistema.LCPService.EnviarResultadoCombate:output_type -> sistema.ResultadoOperacion
	11, // 16: sistema.LCPService.VerificarEntrenadores:output_type -> sistema.ResultadoVerificacion
	13, // 17: sistema.LCPService.NotificarCambioRanking:output_type -> sistema.RankingUpdateResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_sistema_proto_init() }
func file_sistema_proto_init() {
	if File_sistema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sistema_proto_rawDesc), len(file_sistema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sistema_proto_goTypes,
		DependencyIndexes: file_sistema_proto_depIdxs,
		MessageInfos:      file_sistema_proto_msgTypes,
	}.Build()
	File_sistema_proto = out.File
	file_sistema_proto_goTypes = nil
	file_sistema_proto_depIdxs = nil
}
